[versions]
compose = "1.10.1"
composeJetbrains = "1.10.0"
composeJetbrainsMaterial3 = "1.9.0"

conventions = "0.0.98"

detekt = "2.0.0-alpha.1"
detektCompose = "0.5.3"
detektEygraber = "1.0.14"

dokka = "2.1.0"

kotlin = "2.3.0"

kotlinx-coroutines = "1.10.2"

ktlint = "1.8.0"

publish = "0.36.0"

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose" }
conventions = { id = "com.eygraber.conventions", version.ref = "conventions" }
conventionsComposeMultiplatform = { id = "com.eygraber.conventions-compose-jetbrains" }
conventionsDetekt = { id = "com.eygraber.conventions-detekt2" }
conventionsKotlin = { id = "com.eygraber.conventions-kotlin-library" }
conventionsPublish = { id = "com.eygraber.conventions-publish-maven-central" }
dependencyAnalysis = { id = "com.autonomousapps.dependency-analysis" }
dependencyAnalysisRoot = { id = "com.autonomousapps.dependency-analysis", version = "3.5.1" }
kotlinJvm = { id = "org.jetbrains.kotlin.jvm" }

[libraries]
buildscript-compose-compiler = { module = "org.jetbrains.kotlin:compose-compiler-gradle-plugin", version.ref = "kotlin" }
buildscript-compose-jetbrains = { module = "org.jetbrains.compose:compose-gradle-plugin", version.ref = "composeJetbrains" }
buildscript-detekt = { module = "dev.detekt:detekt-gradle-plugin", version.ref = "detekt" }
buildscript-dokka = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
buildscript-kotlin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
buildscript-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "publish" }

compose-foundation = { module = "org.jetbrains.compose.foundation:foundation-desktop", version.ref = "composeJetbrains" }
compose-foundationLayout = { module = "org.jetbrains.compose.foundation:foundation-layout-desktop", version.ref = "composeJetbrains" }
compose-material3 = { module = "org.jetbrains.compose.material3:material3-desktop", version.ref = "composeJetbrainsMaterial3" }
compose-runtime = { module = "androidx.compose.runtime:runtime-desktop", version.ref = "compose" }
compose-runtimeAnnotations = { module = "androidx.compose.runtime:runtime-annotation", version.ref = "compose" }
compose-ui = { module = "org.jetbrains.compose.ui:ui-desktop", version.ref = "composeJetbrains" }
compose-ui-graphics = { module = "org.jetbrains.compose.ui:ui-graphics-desktop", version.ref = "composeJetbrains" }
compose-ui-text = { module = "org.jetbrains.compose.ui:ui-text-desktop", version.ref = "composeJetbrains" }
compose-ui-unit = { module = "org.jetbrains.compose.ui:ui-unit-desktop", version.ref = "composeJetbrains" }
compose-ui-util = { module = "org.jetbrains.compose.ui:ui-util-desktop", version.ref = "composeJetbrains" }

detektCompose = { module = "io.nlopez.compose.rules:detekt", version.ref = "detektCompose" }
detektEygraber-formatting = { module = "com.eygraber.detekt.rules:formatting", version.ref = "detektEygraber" }
detektEygraber-style = { module = "com.eygraber.detekt.rules:style", version.ref = "detektEygraber" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-swing = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }

# not actually used; just here so renovate picks it up
ktlint = { module = "com.pinterest.ktlint:ktlint-bom", version.ref = "ktlint" }

test-junit = "junit:junit:4.13.2"
